#Github action to add/remove labels to issues

safe_loading:
    - '(Safe loading issue)'
token_balance:
    - '(Token balance not up-to-date)'
token_missing:
    - '(Token missing completely)'
tx_execution:
    - '(Transaction execution issue)'
tx_missing:
    - '(Transaction missing / not visible in app or service)'
other:
    - '(Other)'
mainnet:
    -  '(Ethereum Mainnet)'   
gnosis_chain:
    - '(Gnosis Chain)' 
polygon:
    - '(Polygon)'
bsc: 
    - '(Binance Smart Chain)'   
goerli:
    - '(Goerli')
