name: Missing Token
description: File a report for a missing token (or balance not up to date)
title: "[Missing Token] The following token is not up to date:"
labels: ["triage", "token", "indexing"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: network
    attributes:
      label: Network
      description: On What network are you experiencing the issue?
      options:
        - Ethereum Mainnet
        - Goerli
        - Gnosis Chain
    validations:
      required: true
  - type: input
    id: safe
    attributes:
      label: Safe Address
      description: What is the Address of your Safe?
      placeholder: ex. 0xbadda...
    validations:
      required: true
  - type: input
    id: token
    attributes:
      label: Token Address
      description: What token is not up to date?
      placeholder: ex. 0xbadda...
    validations:
      required: true
  - type: dropdown
    id: issue_type
    attributes:
      label: What issue are you experiencing?
      multiple: true
      options:
        - Missing completely / Not visible in the interface or service
        - Balance not up-to-date in the interface or service
    validations:
      required: true
  - type: textarea
    id: transfers
    attributes:
      label: Transfers
      description: Please copy links to the transfers that of the token that you are missing
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
